---
- name: show bgp neigh test
  hosts: eos_devices
    
  tasks:
    - name: "show bgp neighbours"
      eos_command:
        commands:
          - show ip bgp summary | json

      register: bgp_output
      
    - name: "show lldp neighbors"
      eos_command:
        commands:
          - show lldp neighbors | json

      register: lldp_output
      
    - name: show bgp output
      debug:
        msg: "{{ output.stdout[0].vrfs.default.peers }}"

    - name: show lldp output
      debug:
        msg: "{{ output.stdout[0].lldpNeighbors }}"
