---
- name: Get facts from ALL devices
  gather_facts: no
  hosts: network

  tasks:
    - name: Gathering facts via eos_facts module
      eos_facts:
      when: ansible_network_os == 'eos'

    - name: Gathering facts via ios_facts module
      ios_facts:
      when: ansible_network_os == 'ios'

    - name: Display certain facts
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} a {{ ansible_net_model }} running {{ ansible_net_version }}"

#    - name: Display all facts for a host
#      debug:
#        var: hostvars['vEOS-SSW01']
