---
- name: Get facts from IOS devices
  gather_facts: no
  hosts: routers
    
  tasks:
    - name: Gathering facts via ios_facts module
      ios_facts:
      when: ansible_network_os == 'ios'

    - name: Display certain facts
      when: ansible_network_os == 'ios'
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} running {{ ansible_net_version }}"

    - name: Display all facts for a host
      when: ansible_network_os == 'ios'
      debug:
        var: hostvars['IOS-RT01']
